import { useEffect, useMemo, useState, type ReactNode } from 'react';
import Chart from '../components/Chart';
import { offlineJson } from '../data/offlineSnapshot';

type DatasetListItem = {id:string;name:string;description?:string;source_type:string;available:boolean;error?:string;capabilities:Record<string,{enabled:boolean;reason?:string}>};
type Metric = {name:string;aggregation:string;field?:string;owner:string;version:string;filter?:string;unit?:string};
type Dataset = DatasetListItem & {version:string;mappings:Record<string,string|string[]>;dimensions:string[];metrics:Record<string,Metric>;quality_rules:Array<Record<string,unknown>>;lineage:{nodes:string[];edges:string[][]};capabilities:Record<string,{enabled:boolean;reason?:string}>};
type MetricResult = {metric_name:string;metric_id:string;rows:Array<Record<string,unknown>>;generated_sql:string};
type Quality = {rules:number;passed:number;warnings:number;failed:number;checks:Array<{id:string;field:string;type:string;severity:string;status:string;failures:number}>};

const API=import.meta.env.VITE_API_BASE || '';
async function getJson<T>(path:string):Promise<T>{
  const controller=new AbortController();const timer=window.setTimeout(()=>controller.abort(),5000);
  try{
    const r=await fetch(`${API}${path}`,{signal:controller.signal});
    if(!r.ok)throw new Error((await r.json().catch(()=>({detail:r.statusText}))).detail||r.statusText);
    return r.json() as Promise<T>;
  }catch(error){
    try{const snapshot=offlineJson(path) as T;window.dispatchEvent(new CustomEvent('growth-intel:snapshot',{detail:String(error)}));return snapshot}
    catch{throw error}
  }finally{window.clearTimeout(timer)}
}
const NAV=[['overview','经营总览'],['sources','数据源管理'],['mapping','字段映射'],['metrics','指标中心'],['analysis','自定义分析'],['funnel','漏斗与留存'],['quality','数据质量'],['lineage','数据血缘'],['about','平台说明']] as const;

function badge(enabled:boolean,reason?:string){return <span title={reason||''} className={`rounded-full px-2 py-1 text-xs ${enabled?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-500'}`}>{enabled?'已启用':`未启用${reason?` · ${reason}`:''}`}</span>}
function fmt(value:unknown){if(typeof value==='number')return new Intl.NumberFormat('zh-CN',{maximumFractionDigits:2}).format(value);return String(value??'—')}
function metricValue(metric:Metric,value:unknown){return metric.unit==='percent'&&typeof value==='number'?`${fmt(value*100)}%`:fmt(value)}
const Panel=({title,children}:{title:string;children:ReactNode})=><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="mb-4 font-semibold">{title}</h3>{children}</section>;

export default function Platform(){
  const [datasets,setDatasets]=useState<DatasetListItem[]>([]);const [datasetId,setDatasetId]=useState('demo_ecommerce');const [dataset,setDataset]=useState<Dataset|null>(null);const [tab,setTab]=useState('overview');const [error,setError]=useState('');const [snapshot,setSnapshot]=useState(false);
  useEffect(()=>{const listener=()=>setSnapshot(true);window.addEventListener('growth-intel:snapshot',listener);return()=>window.removeEventListener('growth-intel:snapshot',listener)},[]);
  useEffect(()=>{getJson<DatasetListItem[]>('/api/v1/datasets').then(setDatasets).catch(e=>setError(String(e)))},[]);
  useEffect(()=>{setError('');getJson<Dataset>(`/api/v1/datasets/${datasetId}`).then(setDataset).catch(e=>setError(String(e)))},[datasetId]);
  return <div className="min-h-screen bg-[#f4f7fb] text-slate-800"><aside className="fixed inset-y-0 left-0 w-64 border-r border-slate-800 bg-[#0b1220] p-5 text-white"><div className="mb-7 flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-cyan-400 font-black text-slate-950">U</div><div><div className="font-semibold">统一经营分析平台</div><div className="text-xs text-slate-400">Metric Governance</div></div></div><nav className="space-y-1">{NAV.map(([key,label])=><button key={key} onClick={()=>setTab(key)} className={`w-full rounded-lg px-3 py-2.5 text-left text-sm ${tab===key?'bg-cyan-400/15 text-cyan-300':'text-slate-400 hover:bg-white/5 hover:text-white'}`}>{label}</button>)}</nav><div className="absolute bottom-5 text-xs leading-5 text-slate-500">CSV · Parquet · SQLite · PostgreSQL<br/>Config-driven semantic layer</div></aside><main className="ml-64 min-h-screen"><header className="sticky top-0 z-10 flex items-center justify-between border-b border-slate-200 bg-white/95 px-8 py-4 backdrop-blur"><div><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[.18em] text-cyan-700">Dataset workspace {snapshot&&<span className="rounded-full bg-amber-100 px-2 py-1 normal-case tracking-normal text-amber-800">离线演示快照</span>}</div><div className="font-semibold">{dataset?.name||'加载中'}</div></div><select value={datasetId} onChange={e=>setDatasetId(e.target.value)} className="rounded-lg border border-slate-300 bg-white px-4 py-2 text-sm">{datasets.map(d=><option key={d.id} value={d.id} disabled={!d.available}>{d.name}{d.available?'':'（后端恢复后可用）'}</option>)}</select></header><div className="mx-auto max-w-7xl p-8">{snapshot&&<div className="mb-5 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">Render 后端当前不可达，界面已自动切换到浏览器内置的 20 条固定演示事件。所有数值仅用于验证交互与指标口径，不伪装成真实业务结论。</div>}{error?<div className="rounded-xl border border-red-200 bg-red-50 p-5 text-red-700">{error}</div>:dataset?<Content tab={tab} dataset={dataset}/>:<div>加载中…</div>}</div></main></div>
}

function Content({tab,dataset}:{tab:string;dataset:Dataset}){if(tab==='overview')return <Overview dataset={dataset}/>;if(tab==='sources')return <Sources dataset={dataset}/>;if(tab==='mapping')return <Mapping dataset={dataset}/>;if(tab==='metrics')return <Metrics dataset={dataset}/>;if(tab==='analysis')return <Analysis dataset={dataset}/>;if(tab==='funnel')return <Funnel dataset={dataset}/>;if(tab==='quality')return <QualityPanel dataset={dataset}/>;if(tab==='lineage')return <Lineage dataset={dataset}/>;return <About dataset={dataset}/>}

function Overview({dataset}:{dataset:Dataset}){const ids=useMemo(()=>Object.keys(dataset.metrics),[dataset.metrics]);const [values,setValues]=useState<Record<string,unknown>>({});useEffect(()=>{Promise.all(ids.slice(0,5).map(id=>getJson<MetricResult>(`/api/v1/datasets/${dataset.id}/metrics/${id}`))).then(rs=>setValues(Object.fromEntries(rs.map(r=>[r.metric_id,r.rows[0]?.value]))))},[dataset.id,ids]);return <><div className="mb-6"><h1 className="text-2xl font-bold">经营总览</h1><p className="mt-1 text-sm text-slate-500">指标、页面和分析能力均由当前数据集配置生成。</p></div><div className="grid grid-cols-5 gap-4">{ids.slice(0,5).map(id=><div key={id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="text-sm text-slate-500">{dataset.metrics[id].name}</div><div className="mt-2 text-2xl font-bold">{metricValue(dataset.metrics[id],values[id])}</div><div className="mt-2 text-xs text-slate-400">v{dataset.metrics[id].version} · {dataset.metrics[id].owner}</div></div>)}</div><div className="mt-6 grid grid-cols-2 gap-5"><Panel title="能力自适应"><div className="flex flex-wrap gap-2">{Object.entries(dataset.capabilities).map(([k,v])=><span key={k}>{badge(v.enabled,v.reason)}</span>)}</div></Panel><Panel title="数据契约"><div className="text-sm leading-7 text-slate-600">数据源：{dataset.source_type}<br/>语义角色：{Object.keys(dataset.mappings).join(' / ')}<br/>指标：{ids.length} 个 · 维度：{dataset.dimensions.length} 个</div></Panel></div></>}

function Sources({dataset}:{dataset:Dataset}){const [schema,setSchema]=useState<Array<Record<string,unknown>>>([]);const [preview,setPreview]=useState<Array<Record<string,unknown>>>([]);useEffect(()=>{getJson<Array<Record<string,unknown>>>(`/api/v1/datasets/${dataset.id}/schema`).then(setSchema);getJson<Array<Record<string,unknown>>>(`/api/v1/datasets/${dataset.id}/preview?limit=5`).then(setPreview)},[dataset.id]);return <><h1 className="mb-6 text-2xl font-bold">数据源管理</h1><div className="grid grid-cols-2 gap-5"><Panel title={`Schema · ${schema.length} 字段`}><div className="max-h-[520px] overflow-auto text-sm">{schema.map((c,i)=><div key={i} className="flex justify-between border-b py-2"><span>{String(c.column_name)}</span><span className="text-slate-400">{String(c.column_type)}</span></div>)}</div></Panel><Panel title="数据预览"><pre className="max-h-[520px] overflow-auto whitespace-pre-wrap text-xs text-slate-600">{JSON.stringify(preview,null,2)}</pre></Panel></div></>}

function Mapping({dataset}:{dataset:Dataset}){return <><h1 className="mb-6 text-2xl font-bold">字段语义映射</h1><Panel title="业务角色 → 物理字段"><div className="grid grid-cols-3 gap-3">{Object.entries(dataset.mappings).map(([role,field])=><div key={role} className="rounded-xl bg-slate-50 p-4"><div className="text-xs uppercase tracking-wide text-slate-400">{role}</div><div className="mt-1 font-mono text-sm">{Array.isArray(field)?field.join(' + '):field}</div></div>)}</div></Panel></>}

function Metrics({dataset}:{dataset:Dataset}){return <><h1 className="mb-6 text-2xl font-bold">指标中心</h1><Panel title={`${Object.keys(dataset.metrics).length} 个受治理指标`}><table className="w-full text-left text-sm"><thead className="text-slate-400"><tr><th className="pb-3">指标</th><th>聚合</th><th>字段/过滤</th><th>负责人</th><th>版本</th></tr></thead><tbody>{Object.entries(dataset.metrics).map(([id,m])=><tr key={id} className="border-t"><td className="py-3"><div className="font-medium">{m.name}</div><div className="font-mono text-xs text-slate-400">{id}</div></td><td>{m.aggregation}</td><td className="font-mono text-xs">{m.field||m.filter||'configured expression'}</td><td>{m.owner}</td><td>{m.version}</td></tr>)}</tbody></table></Panel></>}

function Analysis({dataset}:{dataset:Dataset}){const metricIds=useMemo(()=>Object.keys(dataset.metrics),[dataset.metrics]);const dimensions=dataset.dimensions;const [metric,setMetric]=useState(metricIds[0]);const [dimension,setDimension]=useState(dimensions[0]||'');const [result,setResult]=useState<MetricResult|null>(null);useEffect(()=>{setMetric(metricIds[0]);setDimension(dimensions[0]||'')},[dataset.id,metricIds,dimensions]);useEffect(()=>{if(metric)getJson<MetricResult>(`/api/v1/datasets/${dataset.id}/metrics/${metric}${dimension?`?dimension=${encodeURIComponent(dimension)}`:''}`).then(setResult)},[dataset.id,metric,dimension]);const chart=useMemo(()=>{const rows=result?.rows||[];return {labels:rows.map(r=>String(r[dimension]??'总计')),values:rows.map(r=>Number(r.value??0))}},[result,dimension]);return <><h1 className="mb-6 text-2xl font-bold">自定义分析</h1><div className="mb-5 flex gap-3"><select className="rounded-lg border px-3 py-2" value={metric} onChange={e=>setMetric(e.target.value)}>{metricIds.map(id=><option key={id} value={id}>{dataset.metrics[id].name}</option>)}</select><select className="rounded-lg border px-3 py-2" value={dimension} onChange={e=>setDimension(e.target.value)}>{dimensions.map(d=><option key={d}>{d}</option>)}</select></div><Panel title="统一图表组件"><Chart labels={chart.labels} values={chart.values} height="420px"/><details className="mt-4 text-xs text-slate-500"><summary>查看后端生成 SQL</summary><pre className="mt-2 overflow-auto rounded bg-slate-50 p-3">{result?.generated_sql}</pre></details></Panel></>}

function Funnel({dataset}:{dataset:Dataset}){const cap=dataset.capabilities.funnel;const [steps,setSteps]=useState<Array<{step:string;users:number}>>([]);useEffect(()=>{if(cap.enabled)getJson<{steps:Array<{step:string;users:number}>}>(`/api/v1/datasets/${dataset.id}/funnel`).then(r=>setSteps(r.steps));else setSteps([])},[dataset.id,cap.enabled]);return <><h1 className="mb-6 text-2xl font-bold">漏斗与留存</h1>{!cap.enabled?<Panel title="模块已自动停用"><div className="text-slate-600">{cap.reason}。平台不会在字段不足时返回错误图表或伪造漏斗。</div></Panel>:<Panel title="同一主体有序漏斗"><div className="space-y-3">{steps.map((x,i)=><div key={x.step} className="flex items-center gap-4"><div className="w-24 text-sm">{x.step}</div><div className="h-9 rounded bg-gradient-to-r from-cyan-400 to-indigo-500" style={{width:`${Math.max(8,80*x.users/(steps[0]?.users||1))}%`}}/><div className="font-semibold">{x.users}</div>{i>0&&<div className="text-xs text-slate-400">{fmt(100*x.users/steps[i-1].users)}%</div>}</div>)}</div></Panel>}</>}

function QualityPanel({dataset}:{dataset:Dataset}){const [q,setQ]=useState<Quality|null>(null);useEffect(()=>{getJson<Quality>(`/api/v1/datasets/${dataset.id}/quality`).then(setQ)},[dataset.id]);return <><h1 className="mb-6 text-2xl font-bold">数据质量</h1>{q&&<><div className="mb-5 grid grid-cols-4 gap-4">{[['规则',q.rules],['通过',q.passed],['警告',q.warnings],['失败',q.failed]].map(x=><div className="rounded-xl border bg-white p-4" key={String(x[0])}><div className="text-sm text-slate-500">{x[0]}</div><div className="text-2xl font-bold">{x[1]}</div></div>)}</div><Panel title="检查明细"><table className="w-full text-sm"><tbody>{q.checks.map(c=><tr key={c.id} className="border-t"><td className="py-3 font-mono">{c.id}</td><td>{c.field}</td><td>{c.type}</td><td>{badge(c.status==='passed',`${c.failures} 条失败`)}</td></tr>)}</tbody></table></Panel></>}</>}

function Lineage({dataset}:{dataset:Dataset}){return <><h1 className="mb-6 text-2xl font-bold">数据血缘</h1><Panel title="ODS → DWD → DWS → ADS"><div className="flex flex-wrap items-center gap-2">{dataset.lineage.nodes.map((n,i)=><span key={n} className="contents"><span className="rounded-xl border border-cyan-200 bg-cyan-50 px-4 py-3 font-mono text-sm text-cyan-900">{n}</span>{i<dataset.lineage.nodes.length-1&&<span className="text-slate-300">→</span>}</span>)}</div></Panel></>}

function About({dataset}:{dataset:Dataset}){return <><h1 className="mb-6 text-2xl font-bold">平台说明</h1><div className="grid grid-cols-2 gap-5"><Panel title="设计原则"><ul className="list-disc space-y-2 pl-5 text-sm leading-6 text-slate-600"><li>统一适配器负责连接、Schema 与预览，业务逻辑不按数据源复制。</li><li>字段映射决定模块能力，缺字段自动禁用并解释原因。</li><li>指标配置由后端生成参数化查询，前端不能提交任意 SQL。</li><li>质量规则、血缘和数据版本随数据集独立管理。</li></ul></Panel><Panel title="当前空间"><pre className="text-xs text-slate-600">{JSON.stringify({id:dataset.id,version:dataset.version,source:dataset.source_type},null,2)}</pre></Panel></div></>}
